name: NCondense
version: '1.0.0'
main: com.nours.ncondense.NCondense
api-version: '1.20'
commands:
  ncondense:
    description: See all Ncondense commands
    usage: Perform /ncondense help or /nc help to see a list of commands!
    default: true
    aliases: [nc]
