name: NCondense
version: '1.0.0'
main: com.nours.ncondense.NCondense
api-version: '1.20'
depend:
  - ProtocolLib
commands:
  ncondense:
    description: See all Ncondense commands
    usage: /ncondense
    permission: ncondense.command
    aliases: [nc]
